CREATE TABLE [ACCOUNT].[ROLE_MODULES]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [IdRole] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[ROLES],
  [IdModule] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[MODULES]
)
