CREATE TABLE [ACCOUNT].[USER_AUDIT_DATA]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [IdAudit] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[USER_AUDIT],
  [IdType] INT NOT NULL FOREIGN KEY REFERENCES [DICT].[AUDIT_DATA_TYPES],
  [JSON] VARCHAR(255)
)
