CREATE TABLE [ACCOUNT].[USERS]
(
  [IdUser] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [Login] VARCHAR(20) NOT NULL,
  [Pass] VARCHAR(32) NOT NULL,
  [IsActive] CHAR(1) NOT NULL,
  [Name] VARCHAR(120) NOT NULL,
  [Desc] VARCHAR(255),
  [PassDate] DATE,
)
