CREATE TABLE [ACCOUNT].[USER_DISTRICTS]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [IdUser] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[USERS],
  [IdDistrict] INT NOT NULL FOREIGN KEY REFERENCES [DICT].[DISTRICTS]
)
