CREATE TABLE [ACCOUNT].[USER_ROLES]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [IdUser] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[USERS],
  [IdRole] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[ROLES]
)
