--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "ACCOUNT"."GROUP_ROLES" DROP CONSTRAINT "GROUP_ROLES_GROUPS_FK";

ALTER TABLE "ACCOUNT"."GROUP_ROLES" DROP CONSTRAINT "GROUP_ROLES_ROLES_FK";

ALTER TABLE "ACCOUNT"."ROLE_MODULES" DROP CONSTRAINT "ROLE_MODULES_MODULES_FK";

ALTER TABLE "ACCOUNT"."ROLE_MODULES" DROP CONSTRAINT "ROLE_MODULES_ROLES_FK";

ALTER TABLE "ACCOUNT"."USER_AUDIT" DROP CONSTRAINT "USER_AUDIT_AUDIT_ACTIONS_FK";

ALTER TABLE "ACCOUNT"."USER_AUDIT" DROP CONSTRAINT "USER_AUDIT_AUDIT_TARGETS_FK";

ALTER TABLE "ACCOUNT"."USER_AUDIT" DROP CONSTRAINT "USER_AUDIT_USERS_FK";

ALTER TABLE "ACCOUNT"."USER_AUDIT_DATA" DROP CONSTRAINT "USER_AUDIT_DATA_USER_AUDIT_FK";

ALTER TABLE "ACCOUNT"."USER_AUDIT_DATA" DROP CONSTRAINT "USER_EVENT_DATA_EVENT_DATA_TYPES_FK";

ALTER TABLE "ACCOUNT"."USER_DISTRICTS" DROP CONSTRAINT "USER_DISTRICTS_DISTRICTS_FK";

ALTER TABLE "ACCOUNT"."USER_DISTRICTS" DROP CONSTRAINT "USER_DISTRICTS_USERS_FK";

ALTER TABLE "ACCOUNT"."USER_GROUPS" DROP CONSTRAINT "USER_GROUPS_GROUPS_FK";

ALTER TABLE "ACCOUNT"."USER_GROUPS" DROP CONSTRAINT "USER_GROUPS_USERS_FK";

ALTER TABLE "ACCOUNT"."USER_ROLES" DROP CONSTRAINT "USER_ROLES_ROLES_FK";

ALTER TABLE "ACCOUNT"."USER_ROLES" DROP CONSTRAINT "USER_ROLES_USERS_FK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_REQUEST_STATES_FK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_REQUEST_TYPES_FK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_USERS_FK";

ALTER TABLE "R"."RSCRIPT_PARAMS" DROP CONSTRAINT "RSCRIPT_PARAM_RSCRIPTS_FK";

ALTER TABLE "R"."RSCRIPT_PARAMS" DROP CONSTRAINT "RSCRIPT_PARAM_RSCRIPT_PARAM_TYPES_FK";

ALTER TABLE "R"."RSCRIPT_TREE" DROP CONSTRAINT "RSCRIPT_TREE_RSCRIPTS_FK";

ALTER TABLE "SAMPLE"."SAMPLE" DROP CONSTRAINT "SAMPLE_SAMPLE_DICTS_FK";

ALTER TABLE "SAMPLE"."SAMPLE" DROP CONSTRAINT "SAMPLE_SAMPLE_TYPES_FK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" DROP CONSTRAINT "SAMPLE_AUDIT_AUDIT_ACTIONS_FK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" DROP CONSTRAINT "SAMPLE_AUDIT_AUDIT_TARGETS_FK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" DROP CONSTRAINT "SAMPLE_AUDIT_SAMPLE_FK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" DROP CONSTRAINT "SAMPLE_AUDIT_USERS_FK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" DROP CONSTRAINT "SAMPLE_AUDIT_DATA_AUDIT_DATA_TYPES_FK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" DROP CONSTRAINT "SAMPLE_AUDIT_DATA_SAMPLE_AUDIT_FK";

ALTER TABLE "SAMPLE"."SAMPLE_CHILD" DROP CONSTRAINT "SAMPLE_CHILD_SAMPLE_FK";

ALTER TABLE "ACCOUNT"."GROUPS" DROP CONSTRAINT "GROUPS_PK";

ALTER TABLE "ACCOUNT"."GROUP_ROLES" DROP CONSTRAINT "GROUP_ROLES_PK";

ALTER TABLE "ACCOUNT"."MODULES" DROP CONSTRAINT "MODULES_PK";

ALTER TABLE "ACCOUNT"."ROLES" DROP CONSTRAINT "ROLES_PK";

ALTER TABLE "ACCOUNT"."ROLE_MODULES" DROP CONSTRAINT "ROLE_MODULES_PK";

ALTER TABLE "ACCOUNT"."USERS" DROP CONSTRAINT "USERS_PK";

ALTER TABLE "ACCOUNT"."USER_AUDIT" DROP CONSTRAINT "USER_EVENTS_PK";

ALTER TABLE "ACCOUNT"."USER_AUDIT_DATA" DROP CONSTRAINT "USER_AUDIT_DATA_PK";

ALTER TABLE "ACCOUNT"."USER_DISTRICTS" DROP CONSTRAINT "USER_DISTRICTS_PK";

ALTER TABLE "ACCOUNT"."USER_GROUPS" DROP CONSTRAINT "USER_GROUPS_PK";

ALTER TABLE "ACCOUNT"."USER_ROLES" DROP CONSTRAINT "USER_ROLES_PK";

ALTER TABLE "DICT"."AUDIT_ACTIONS" DROP CONSTRAINT "AUDIT_ACTIONS_PK";

ALTER TABLE "DICT"."AUDIT_DATA_TYPES" DROP CONSTRAINT "AUDIT_DATA_TYPES_PK";

ALTER TABLE "DICT"."AUDIT_TARGETS" DROP CONSTRAINT "AUDIT_TARGETS_PK";

ALTER TABLE "DICT"."DISTRICTS" DROP CONSTRAINT "DISTRICTS_PK";

ALTER TABLE "DICT"."REQUEST_STATES" DROP CONSTRAINT "REQUEST_STATES_PK";

ALTER TABLE "DICT"."REQUEST_TYPES" DROP CONSTRAINT "REQUEST_TYPES_PK";

ALTER TABLE "DICT"."RSCRIPT_PARAM_TYPES" DROP CONSTRAINT "RSCRIPT_PARAM_TYPES_PK";

ALTER TABLE "DICT"."SAMPLE_DICTS" DROP CONSTRAINT "SAMPLE_DICTS_PK";

ALTER TABLE "DICT"."SAMPLE_TYPES" DROP CONSTRAINT "SAMPLE_TYPES_PK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_PK";

ALTER TABLE "R"."RSCRIPTS" DROP CONSTRAINT "RSCRIPTS_PK";

ALTER TABLE "R"."RSCRIPT_PARAMS" DROP CONSTRAINT "RSCRIPT_PARAMS_PK";

ALTER TABLE "R"."RSCRIPT_TREE" DROP CONSTRAINT "RSCRIPT_TREE_PK";

ALTER TABLE "SAMPLE"."SAMPLE" DROP CONSTRAINT "SAMPLE_PK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" DROP CONSTRAINT "SAMPLE_AUDIT_PK";

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" DROP CONSTRAINT "SAMPLE_AUDIT_DATA_PK";

ALTER TABLE "SAMPLE"."SAMPLE_CHILD" DROP CONSTRAINT "SAMPLE_CHILD_PK";

DROP VIEW "ACCOUNT"."V_AUDIT";

DROP VIEW "ACCOUNT"."V_AUDIT_DATA";

DROP TABLE "ACCOUNT"."GROUPS";

DROP TABLE "ACCOUNT"."GROUP_ROLES";

DROP TABLE "ACCOUNT"."MODULES";

DROP TABLE "ACCOUNT"."ROLES";

DROP TABLE "ACCOUNT"."ROLE_MODULES";

DROP TABLE "ACCOUNT"."USERS";

DROP TABLE "ACCOUNT"."USER_AUDIT";

DROP TABLE "ACCOUNT"."USER_AUDIT_DATA";

DROP TABLE "ACCOUNT"."USER_DISTRICTS";

DROP TABLE "ACCOUNT"."USER_GROUPS";

DROP TABLE "ACCOUNT"."USER_ROLES";

DROP TABLE "DICT"."AUDIT_ACTIONS";

DROP TABLE "DICT"."AUDIT_DATA_TYPES";

DROP TABLE "DICT"."AUDIT_TARGETS";

DROP TABLE "DICT"."DISTRICTS";

DROP TABLE "DICT"."REQUEST_STATES";

DROP TABLE "DICT"."REQUEST_TYPES";

DROP TABLE "DICT"."RSCRIPT_PARAM_TYPES";

DROP TABLE "DICT"."SAMPLE_DICTS";

DROP TABLE "DICT"."SAMPLE_TYPES";

DROP TABLE "MQ"."REQUESTS";

DROP TABLE "R"."RSCRIPTS";

DROP TABLE "R"."RSCRIPT_PARAMS";

DROP TABLE "R"."RSCRIPT_TREE";

DROP TABLE "SAMPLE"."SAMPLE";

DROP TABLE "SAMPLE"."SAMPLE_AUDIT";

DROP TABLE "SAMPLE"."SAMPLE_AUDIT_DATA";

DROP TABLE "SAMPLE"."SAMPLE_CHILD";

DROP SCHEMA "ACCOUNT" RESTRICT;

DROP SCHEMA "DICT" RESTRICT;

DROP SCHEMA "MQ" RESTRICT;

DROP SCHEMA "R" RESTRICT;

DROP SCHEMA "SAMPLE" RESTRICT;

CREATE SCHEMA "ACCOUNT";

CREATE SCHEMA "DICT";

CREATE SCHEMA "MQ";

CREATE SCHEMA "R";

CREATE SCHEMA "SAMPLE";

CREATE TABLE "ACCOUNT"."GROUPS" (
		"ID_GROUP" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."GROUP_ROLES" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_GROUP" BIGINT NOT NULL, 
		"ID_ROLE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."MODULES" (
		"ID_MODULE" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."ROLES" (
		"ID_ROLE" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."ROLE_MODULES" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_ROLE" BIGINT NOT NULL, 
		"ID_MODULE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USERS" (
		"ID_USER" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"LOGIN" VARCHAR(20) NOT NULL, 
		"PASS" VARCHAR(32) NOT NULL, 
		"IS_ACTIVE" CHAR(1) NOT NULL, 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255), 
		"PASS_DATE" DATE
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_AUDIT" (
		"ID_AUDIT" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_TARGET" INTEGER NOT NULL, 
		"ID_ACTION" INTEGER NOT NULL, 
		"STAMP" TIMESTAMP NOT NULL, 
		"TARGET_ID" BIGINT, 
		"TARGET_NAME" VARCHAR(255), 
		"MESSAGE" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_AUDIT_DATA" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_AUDIT" BIGINT NOT NULL, 
		"ID_TYPE" INTEGER NOT NULL, 
		"JSON" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_DISTRICTS" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_DISTRICT" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_GROUPS" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_GROUP" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_ROLES" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_ROLE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."AUDIT_ACTIONS" (
		"ID_ACTION" INTEGER NOT NULL, 
		"ACTION" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."AUDIT_DATA_TYPES" (
		"ID_TYPE" INTEGER NOT NULL, 
		"TYPE" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."AUDIT_TARGETS" (
		"ID_TARGET" INTEGER NOT NULL, 
		"TARGET" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."DISTRICTS" (
		"ID_DISTRICT" INTEGER NOT NULL, 
		"NAME" VARCHAR(200) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."REQUEST_STATES" (
		"ID_STATE" INTEGER NOT NULL, 
		"STATE" VARCHAR(100) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."REQUEST_TYPES" (
		"ID_TYPE" INTEGER NOT NULL, 
		"TYPE" VARCHAR(100) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."RSCRIPT_PARAM_TYPES" (
		"ID_TYPE" INTEGER NOT NULL, 
		"TYPE" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."SAMPLE_DICTS" (
		"ID_DICT" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"DICT" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."SAMPLE_TYPES" (
		"ID_TYPE" INTEGER NOT NULL, 
		"TYPE" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "MQ"."REQUESTS" (
		"ID_REQUEST" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_TYPE" INTEGER NOT NULL, 
		"ID_STATE" INTEGER NOT NULL, 
		"JSON" VARCHAR(500), 
		"GUID" VARCHAR(100), 
		"CREATED" TIMESTAMP NOT NULL, 
		"PROCESSED" TIMESTAMP, 
		"DELIVERED" TIMESTAMP, 
		"MESSAGE" VARCHAR(500)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "R"."RSCRIPTS" (
		"ID_RSCRIPT" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"SCRIPT_FILE" VARCHAR(255) NOT NULL, 
		"NAME" VARCHAR(120) NOT NULL, 
		"CONTENT_TYPE" VARCHAR(50) NOT NULL, 
		"RESULT_FILE" VARCHAR(200) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "R"."RSCRIPT_PARAMS" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_RSCRIPT" BIGINT NOT NULL, 
		"ID_TYPE" INTEGER NOT NULL, 
		"NAME" VARCHAR(120) NOT NULL, 
		"HINT" VARCHAR(255), 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "R"."RSCRIPT_TREE" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_PARENT" BIGINT, 
		"ID_RSCRIPT" BIGINT, 
		"NAME" VARCHAR(120) NOT NULL, 
		"MODULES" VARCHAR(255), 
		"ICON" VARCHAR(50), 
		"COLOR" VARCHAR(50), 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "SAMPLE"."SAMPLE" (
		"ID_SAMPLE" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY , 
		"ID_TYPE" INTEGER NOT NULL, 
		"ID_DICT" BIGINT NOT NULL, 
		"TEXT" VARCHAR(120), 
		"NUMBER" BIGINT, 
		"DATE" DATE, 
		"TIMESTAMP" TIMESTAMP, 
		"SUM" DECIMAL(10 , 2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "SAMPLE"."SAMPLE_AUDIT" (
		"ID_AUDIT" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY , 
		"ID_USER" BIGINT NOT NULL, 
		"ID_TARGET" INTEGER NOT NULL, 
		"ID_ACTION" INTEGER NOT NULL, 
		"STAMP" TIMESTAMP NOT NULL, 
		"TARGET_ID" BIGINT, 
		"TARGET_NAME" VARCHAR(255), 
		"MESSAGE" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY , 
		"ID_AUDIT" BIGINT NOT NULL, 
		"ID_TYPE" INTEGER NOT NULL, 
		"JSON" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "SAMPLE"."SAMPLE_CHILD" (
		"ID_CHILD" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY , 
		"ID_SAMPLE" BIGINT NOT NULL, 
		"TEXT" VARCHAR(120)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "ACCOUNT"."GROUPS" ADD CONSTRAINT "GROUPS_PK" PRIMARY KEY
	("ID_GROUP");

ALTER TABLE "ACCOUNT"."GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."MODULES" ADD CONSTRAINT "MODULES_PK" PRIMARY KEY
	("ID_MODULE");

ALTER TABLE "ACCOUNT"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY
	("ID_ROLE");

ALTER TABLE "ACCOUNT"."ROLE_MODULES" ADD CONSTRAINT "ROLE_MODULES_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY
	("ID_USER");

ALTER TABLE "ACCOUNT"."USER_AUDIT" ADD CONSTRAINT "USER_EVENTS_PK" PRIMARY KEY
	("ID_AUDIT");

ALTER TABLE "ACCOUNT"."USER_AUDIT_DATA" ADD CONSTRAINT "USER_AUDIT_DATA_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."USER_DISTRICTS" ADD CONSTRAINT "USER_DISTRICTS_PK" PRIMARY KEY
	("ID_USER", 
	 "ID_DISTRICT", 
	 "ID");

ALTER TABLE "ACCOUNT"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_PK" PRIMARY KEY
	("ID");

ALTER TABLE "DICT"."AUDIT_ACTIONS" ADD CONSTRAINT "AUDIT_ACTIONS_PK" PRIMARY KEY
	("ID_ACTION");

ALTER TABLE "DICT"."AUDIT_DATA_TYPES" ADD CONSTRAINT "AUDIT_DATA_TYPES_PK" PRIMARY KEY
	("ID_TYPE");

ALTER TABLE "DICT"."AUDIT_TARGETS" ADD CONSTRAINT "AUDIT_TARGETS_PK" PRIMARY KEY
	("ID_TARGET");

ALTER TABLE "DICT"."DISTRICTS" ADD CONSTRAINT "DISTRICTS_PK" PRIMARY KEY
	("ID_DISTRICT");

ALTER TABLE "DICT"."REQUEST_STATES" ADD CONSTRAINT "REQUEST_STATES_PK" PRIMARY KEY
	("ID_STATE");

ALTER TABLE "DICT"."REQUEST_TYPES" ADD CONSTRAINT "REQUEST_TYPES_PK" PRIMARY KEY
	("ID_TYPE");

ALTER TABLE "DICT"."RSCRIPT_PARAM_TYPES" ADD CONSTRAINT "RSCRIPT_PARAM_TYPES_PK" PRIMARY KEY
	("ID_TYPE");

ALTER TABLE "DICT"."SAMPLE_DICTS" ADD CONSTRAINT "SAMPLE_DICTS_PK" PRIMARY KEY
	("ID_DICT");

ALTER TABLE "DICT"."SAMPLE_TYPES" ADD CONSTRAINT "SAMPLE_TYPES_PK" PRIMARY KEY
	("ID_TYPE");

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_PK" PRIMARY KEY
	("ID_REQUEST");

ALTER TABLE "R"."RSCRIPTS" ADD CONSTRAINT "RSCRIPTS_PK" PRIMARY KEY
	("ID_RSCRIPT");

ALTER TABLE "R"."RSCRIPT_PARAMS" ADD CONSTRAINT "RSCRIPT_PARAMS_PK" PRIMARY KEY
	("ID");

ALTER TABLE "R"."RSCRIPT_TREE" ADD CONSTRAINT "RSCRIPT_TREE_PK" PRIMARY KEY
	("ID");

ALTER TABLE "SAMPLE"."SAMPLE" ADD CONSTRAINT "SAMPLE_PK" PRIMARY KEY
	("ID_SAMPLE");

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" ADD CONSTRAINT "SAMPLE_AUDIT_PK" PRIMARY KEY
	("ID_AUDIT");

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" ADD CONSTRAINT "SAMPLE_AUDIT_DATA_PK" PRIMARY KEY
	("ID");

ALTER TABLE "SAMPLE"."SAMPLE_CHILD" ADD CONSTRAINT "SAMPLE_CHILD_PK" PRIMARY KEY
	("ID_CHILD");

ALTER TABLE "ACCOUNT"."GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_GROUPS_FK" FOREIGN KEY
	("ID_GROUP")
	REFERENCES "ACCOUNT"."GROUPS"
	("ID_GROUP")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_ROLES_FK" FOREIGN KEY
	("ID_ROLE")
	REFERENCES "ACCOUNT"."ROLES"
	("ID_ROLE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."ROLE_MODULES" ADD CONSTRAINT "ROLE_MODULES_MODULES_FK" FOREIGN KEY
	("ID_MODULE")
	REFERENCES "ACCOUNT"."MODULES"
	("ID_MODULE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."ROLE_MODULES" ADD CONSTRAINT "ROLE_MODULES_ROLES_FK" FOREIGN KEY
	("ID_ROLE")
	REFERENCES "ACCOUNT"."ROLES"
	("ID_ROLE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_AUDIT" ADD CONSTRAINT "USER_AUDIT_AUDIT_ACTIONS_FK" FOREIGN KEY
	("ID_ACTION")
	REFERENCES "DICT"."AUDIT_ACTIONS"
	("ID_ACTION")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_AUDIT" ADD CONSTRAINT "USER_AUDIT_AUDIT_TARGETS_FK" FOREIGN KEY
	("ID_TARGET")
	REFERENCES "DICT"."AUDIT_TARGETS"
	("ID_TARGET")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_AUDIT" ADD CONSTRAINT "USER_AUDIT_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_AUDIT_DATA" ADD CONSTRAINT "USER_AUDIT_DATA_USER_AUDIT_FK" FOREIGN KEY
	("ID_AUDIT")
	REFERENCES "ACCOUNT"."USER_AUDIT"
	("ID_AUDIT")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_AUDIT_DATA" ADD CONSTRAINT "USER_EVENT_DATA_EVENT_DATA_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."AUDIT_DATA_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_DISTRICTS" ADD CONSTRAINT "USER_DISTRICTS_DISTRICTS_FK" FOREIGN KEY
	("ID_DISTRICT")
	REFERENCES "DICT"."DISTRICTS"
	("ID_DISTRICT")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_DISTRICTS" ADD CONSTRAINT "USER_DISTRICTS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_GROUPS_FK" FOREIGN KEY
	("ID_GROUP")
	REFERENCES "ACCOUNT"."GROUPS"
	("ID_GROUP")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_ROLES_FK" FOREIGN KEY
	("ID_ROLE")
	REFERENCES "ACCOUNT"."ROLES"
	("ID_ROLE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_REQUEST_STATES_FK" FOREIGN KEY
	("ID_STATE")
	REFERENCES "DICT"."REQUEST_STATES"
	("ID_STATE")
	ON DELETE CASCADE;

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_REQUEST_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."REQUEST_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "R"."RSCRIPT_PARAMS" ADD CONSTRAINT "RSCRIPT_PARAM_RSCRIPTS_FK" FOREIGN KEY
	("ID_RSCRIPT")
	REFERENCES "R"."RSCRIPTS"
	("ID_RSCRIPT")
	ON DELETE CASCADE;

ALTER TABLE "R"."RSCRIPT_PARAMS" ADD CONSTRAINT "RSCRIPT_PARAM_RSCRIPT_PARAM_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."RSCRIPT_PARAM_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "R"."RSCRIPT_TREE" ADD CONSTRAINT "RSCRIPT_TREE_RSCRIPTS_FK" FOREIGN KEY
	("ID_RSCRIPT")
	REFERENCES "R"."RSCRIPTS"
	("ID_RSCRIPT")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE" ADD CONSTRAINT "SAMPLE_SAMPLE_DICTS_FK" FOREIGN KEY
	("ID_DICT")
	REFERENCES "DICT"."SAMPLE_DICTS"
	("ID_DICT")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE" ADD CONSTRAINT "SAMPLE_SAMPLE_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."SAMPLE_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" ADD CONSTRAINT "SAMPLE_AUDIT_AUDIT_ACTIONS_FK" FOREIGN KEY
	("ID_ACTION")
	REFERENCES "DICT"."AUDIT_ACTIONS"
	("ID_ACTION")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" ADD CONSTRAINT "SAMPLE_AUDIT_AUDIT_TARGETS_FK" FOREIGN KEY
	("ID_TARGET")
	REFERENCES "DICT"."AUDIT_TARGETS"
	("ID_TARGET")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" ADD CONSTRAINT "SAMPLE_AUDIT_SAMPLE_FK" FOREIGN KEY
	("TARGET_ID")
	REFERENCES "SAMPLE"."SAMPLE"
	("ID_SAMPLE")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT" ADD CONSTRAINT "SAMPLE_AUDIT_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" ADD CONSTRAINT "SAMPLE_AUDIT_DATA_AUDIT_DATA_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."AUDIT_DATA_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" ADD CONSTRAINT "SAMPLE_AUDIT_DATA_SAMPLE_AUDIT_FK" FOREIGN KEY
	("ID_AUDIT")
	REFERENCES "SAMPLE"."SAMPLE_AUDIT"
	("ID_AUDIT")
	ON DELETE CASCADE;

ALTER TABLE "SAMPLE"."SAMPLE_CHILD" ADD CONSTRAINT "SAMPLE_CHILD_SAMPLE_FK" FOREIGN KEY
	("ID_SAMPLE")
	REFERENCES "SAMPLE"."SAMPLE"
	("ID_SAMPLE")
	ON DELETE CASCADE;

CREATE VIEW "ACCOUNT"."V_AUDIT" ("SRS", "ID_AUDIT", "ID_USER", "ID_TARGET", "ID_ACTION", "STAMP", "TARGET_ID", "TARGET_NAME", "MESSAGE") AS
SELECT
 'USER' as SRS,
 U.* 
FROM ACCOUNT.USER_AUDIT U
UNION ALL
SELECT
 'SAMPLE' as SRS,
 S.* 
FROM SAMPLE.SAMPLE_AUDIT S;

CREATE VIEW "ACCOUNT"."V_AUDIT_DATA" ("SRS", "ID", "ID_AUDIT", "ID_TYPE", "JSON") AS
SELECT
 'USER' as SRS,
 U.* 
FROM ACCOUNT.USER_AUDIT_DATA U
UNION ALL
SELECT
 'SAMPLE' as SRS,
 S.* 
FROM SAMPLE.SAMPLE_AUDIT_DATA S;

COMMENT ON COLUMN "ACCOUNT"."GROUPS"."DESC" IS
'Group description';

COMMENT ON COLUMN "ACCOUNT"."GROUPS"."ID_GROUP" IS
'Identity field of a group';

COMMENT ON COLUMN "ACCOUNT"."GROUPS"."NAME" IS
'Group name';

COMMENT ON COLUMN "ACCOUNT"."GROUP_ROLES"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."GROUP_ROLES"."ID_GROUP" IS
'Foreign key to access group';

COMMENT ON COLUMN "ACCOUNT"."GROUP_ROLES"."ID_ROLE" IS
'Foreign key to access role';

COMMENT ON COLUMN "ACCOUNT"."MODULES"."DESC" IS
'Description of module';

COMMENT ON COLUMN "ACCOUNT"."MODULES"."ID_MODULE" IS
'Identity field of module';

COMMENT ON COLUMN "ACCOUNT"."MODULES"."NAME" IS
'Name of module';

COMMENT ON COLUMN "ACCOUNT"."ROLES"."DESC" IS
'Role description';

COMMENT ON COLUMN "ACCOUNT"."ROLES"."ID_ROLE" IS
'Identity field of a role';

COMMENT ON COLUMN "ACCOUNT"."ROLES"."NAME" IS
'Role name';

COMMENT ON COLUMN "ACCOUNT"."ROLE_MODULES"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."ROLE_MODULES"."ID_MODULE" IS
'Foreign key to access module';

COMMENT ON COLUMN "ACCOUNT"."ROLE_MODULES"."ID_ROLE" IS
'Foreign key to access role';

COMMENT ON COLUMN "ACCOUNT"."USERS"."DESC" IS
'Description of user';

COMMENT ON COLUMN "ACCOUNT"."USERS"."ID_USER" IS
'Identification field of user';

COMMENT ON COLUMN "ACCOUNT"."USERS"."IS_ACTIVE" IS
'Is user active (T - yes F - no)';

COMMENT ON COLUMN "ACCOUNT"."USERS"."LOGIN" IS
'Login field';

COMMENT ON COLUMN "ACCOUNT"."USERS"."NAME" IS
'User name (as shown in application, different from the field user was authorized with)';

COMMENT ON COLUMN "ACCOUNT"."USERS"."PASS" IS
'User password (stored as hash)';

COMMENT ON COLUMN "ACCOUNT"."USERS"."PASS_DATE" IS
'Password expiration date';

COMMENT ON COLUMN "ACCOUNT"."USER_DISTRICTS"."ID" IS
'Indentity field of a link';

COMMENT ON COLUMN "ACCOUNT"."USER_DISTRICTS"."ID_DISTRICT" IS
'Raion number';

COMMENT ON COLUMN "ACCOUNT"."USER_DISTRICTS"."ID_USER" IS
'Foreign key to user';

COMMENT ON COLUMN "ACCOUNT"."USER_GROUPS"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."USER_GROUPS"."ID_GROUP" IS
'Foreign key to access group';

COMMENT ON COLUMN "ACCOUNT"."USER_GROUPS"."ID_USER" IS
'Foreign key to user';

COMMENT ON COLUMN "ACCOUNT"."USER_ROLES"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."USER_ROLES"."ID_ROLE" IS
'Foreign key to access role';

COMMENT ON COLUMN "ACCOUNT"."USER_ROLES"."ID_USER" IS
'Foreign key to user';

COMMENT ON COLUMN "DICT"."DISTRICTS"."ID_DISTRICT" IS
'Raion number';

COMMENT ON COLUMN "DICT"."DISTRICTS"."NAME" IS
'Raion name';

COMMENT ON COLUMN "DICT"."REQUEST_STATES"."DESC" IS
'State description';

COMMENT ON COLUMN "DICT"."REQUEST_STATES"."ID_STATE" IS
'Identity of state';

COMMENT ON COLUMN "DICT"."REQUEST_STATES"."STATE" IS
'State name';

COMMENT ON COLUMN "DICT"."REQUEST_TYPES"."DESC" IS
'Type description';

COMMENT ON COLUMN "DICT"."REQUEST_TYPES"."ID_TYPE" IS
'Identity of type';

COMMENT ON COLUMN "DICT"."REQUEST_TYPES"."TYPE" IS
'Type name';

COMMENT ON COLUMN "MQ"."REQUESTS"."CREATED" IS
'Date and time of creating request';

COMMENT ON COLUMN "MQ"."REQUESTS"."DELIVERED" IS
'Date and time of delivering request result';

COMMENT ON COLUMN "MQ"."REQUESTS"."GUID" IS
'GUID of request';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_REQUEST" IS
'Identity of request';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_STATE" IS
'Identity of state';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_TYPE" IS
'Identity of type';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_USER" IS
'Foreign key to user who created the request';

COMMENT ON COLUMN "MQ"."REQUESTS"."JSON" IS
'JSON parameters of request';

COMMENT ON COLUMN "MQ"."REQUESTS"."MESSAGE" IS
'Message';

COMMENT ON COLUMN "MQ"."REQUESTS"."PROCESSED" IS
'Date and time of finishing processing request';

COMMENT ON SCHEMA "ACCOUNT" IS
'Tables for storing application access data';

COMMENT ON SCHEMA "DICT" IS
'Tables for storing dictionaries';

COMMENT ON SCHEMA "MQ" IS
'Tables for storing message query related data';

COMMENT ON SCHEMA "R" IS
'Tables for storing information about R scripts';

COMMENT ON SCHEMA "SAMPLE" IS
'Tables for storing sample';

COMMENT ON TABLE "ACCOUNT"."GROUPS" IS
'Table of user groups (used to group application roles into access groups)';

COMMENT ON TABLE "ACCOUNT"."GROUP_ROLES" IS
'Table of grouping roles into groups';

COMMENT ON TABLE "ACCOUNT"."MODULES" IS
'Table of modules in application (this is used in frontend application to grant or deny access to certain functions)';

COMMENT ON TABLE "ACCOUNT"."ROLES" IS
'Table of user roles (used to group modules into access roles)';

COMMENT ON TABLE "ACCOUNT"."ROLE_MODULES" IS
'Table of grouping modules into roles';

COMMENT ON TABLE "ACCOUNT"."USERS" IS
'Table of application users';

COMMENT ON TABLE "ACCOUNT"."USER_AUDIT" IS
'Table of general audit
';

COMMENT ON TABLE "ACCOUNT"."USER_AUDIT_DATA" IS
'Table of general audit data';

COMMENT ON TABLE "ACCOUNT"."USER_DISTRICTS" IS
'Table of linking users to raion dictionary';

COMMENT ON TABLE "ACCOUNT"."USER_GROUPS" IS
'Table of linking users to access groups';

COMMENT ON TABLE "ACCOUNT"."USER_ROLES" IS
'Table of linking users to access roles (in addition to all roles that were provided in user''s access group)';

COMMENT ON TABLE "ACCOUNT"."V_AUDIT" IS
'View of all audit';

COMMENT ON TABLE "ACCOUNT"."V_AUDIT_DATA" IS
'View of all audit data';

COMMENT ON TABLE "DICT"."AUDIT_ACTIONS" IS
'Dictionary of audit actions';

COMMENT ON TABLE "DICT"."AUDIT_DATA_TYPES" IS
'Dictionary of audit data types';

COMMENT ON TABLE "DICT"."AUDIT_TARGETS" IS
'Dictionary of audit targets';

COMMENT ON TABLE "DICT"."DISTRICTS" IS
'Dictionary of raions';

COMMENT ON TABLE "DICT"."REQUEST_STATES" IS
'Dictionary of message query request states';

COMMENT ON TABLE "DICT"."REQUEST_TYPES" IS
'Dictionary of message query request types';

COMMENT ON TABLE "DICT"."RSCRIPT_PARAM_TYPES" IS
'Dictionary of R script parameter types';

COMMENT ON TABLE "DICT"."SAMPLE_DICTS" IS
'Dictionary for sample';

COMMENT ON TABLE "DICT"."SAMPLE_TYPES" IS
'Dictionary of sample types';

COMMENT ON TABLE "MQ"."REQUESTS" IS
'Table of message query requests';

COMMENT ON TABLE "SAMPLE"."SAMPLE" IS
'Table of sample';

COMMENT ON TABLE "SAMPLE"."SAMPLE_AUDIT" IS
'Table of sample audit';

COMMENT ON TABLE "SAMPLE"."SAMPLE_AUDIT_DATA" IS
'Table of sample audit data';

COMMENT ON TABLE "SAMPLE"."SAMPLE_CHILD" IS
'Table of sample child';

