--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "ACCOUNT"."GROUP_ROLES" DROP CONSTRAINT "GROUP_ROLES_GROUPS_FK";

ALTER TABLE "ACCOUNT"."GROUP_ROLES" DROP CONSTRAINT "GROUP_ROLES_ROLES_FK";

ALTER TABLE "ACCOUNT"."ROLE_MODULES" DROP CONSTRAINT "ROLE_MODULES_MODULES_FK";

ALTER TABLE "ACCOUNT"."ROLE_MODULES" DROP CONSTRAINT "ROLE_MODULES_ROLES_FK";

ALTER TABLE "ACCOUNT"."USER_EVENTS" DROP CONSTRAINT "USER_EVENTS_EVENT_ACTIONS_FK";

ALTER TABLE "ACCOUNT"."USER_EVENTS" DROP CONSTRAINT "USER_EVENTS_EVENT_TARGETS_FK";

ALTER TABLE "ACCOUNT"."USER_EVENTS" DROP CONSTRAINT "USER_EVENTS_USERS_FK";

ALTER TABLE "ACCOUNT"."USER_EVENT_DATA" DROP CONSTRAINT "USER_EVENT_DATA_EVENT_DATA_TYPES_FK";

ALTER TABLE "ACCOUNT"."USER_EVENT_DATA" DROP CONSTRAINT "USER_EVENT_DATA_USER_EVENTS_FK";

ALTER TABLE "ACCOUNT"."USER_GROUPS" DROP CONSTRAINT "USER_GROUPS_GROUPS_FK";

ALTER TABLE "ACCOUNT"."USER_GROUPS" DROP CONSTRAINT "USER_GROUPS_USERS_FK";

ALTER TABLE "ACCOUNT"."USER_RAIONS" DROP CONSTRAINT "USER_RAIONS_RAIONS_FK";

ALTER TABLE "ACCOUNT"."USER_RAIONS" DROP CONSTRAINT "USER_RAIONS_USERS_FK";

ALTER TABLE "ACCOUNT"."USER_ROLES" DROP CONSTRAINT "USER_ROLES_ROLES_FK";

ALTER TABLE "ACCOUNT"."USER_ROLES" DROP CONSTRAINT "USER_ROLES_USERS_FK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_REQUEST_STATES_FK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_REQUEST_TYPES_FK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_USERS_FK";

ALTER TABLE "ACCOUNT"."GROUPS" DROP CONSTRAINT "GROUPS_PK";

ALTER TABLE "ACCOUNT"."GROUP_ROLES" DROP CONSTRAINT "GROUP_ROLES_PK";

ALTER TABLE "ACCOUNT"."MODULES" DROP CONSTRAINT "MODULES_PK";

ALTER TABLE "ACCOUNT"."ROLES" DROP CONSTRAINT "ROLES_PK";

ALTER TABLE "ACCOUNT"."ROLE_MODULES" DROP CONSTRAINT "ROLE_MODULES_PK";

ALTER TABLE "ACCOUNT"."USERS" DROP CONSTRAINT "USERS_PK";

ALTER TABLE "ACCOUNT"."USER_EVENTS" DROP CONSTRAINT "USER_EVENTS_PK";

ALTER TABLE "ACCOUNT"."USER_EVENT_DATA" DROP CONSTRAINT "USER_EVENT_ACTIONS_PK";

ALTER TABLE "ACCOUNT"."USER_GROUPS" DROP CONSTRAINT "USER_GROUPS_PK";

ALTER TABLE "ACCOUNT"."USER_RAIONS" DROP CONSTRAINT "USER_RAIONS_PK";

ALTER TABLE "ACCOUNT"."USER_ROLES" DROP CONSTRAINT "USER_ROLES_PK";

ALTER TABLE "DICT"."EVENT_ACTIONS" DROP CONSTRAINT "EVENT_ACTIONS_PK";

ALTER TABLE "DICT"."EVENT_DATA_TYPES" DROP CONSTRAINT "EVENT_DATA_TYPES_PK";

ALTER TABLE "DICT"."EVENT_TARGETS" DROP CONSTRAINT "ACTIVITY_TARGETS_PK";

ALTER TABLE "DICT"."RAIONS" DROP CONSTRAINT "RAIONS_PK";

ALTER TABLE "DICT"."REQUEST_STATES" DROP CONSTRAINT "REQUEST_STATES_PK";

ALTER TABLE "DICT"."REQUEST_TYPES" DROP CONSTRAINT "REQUEST_TYPES_PK";

ALTER TABLE "MQ"."REQUESTS" DROP CONSTRAINT "REQUESTS_PK";

DROP TABLE "ACCOUNT"."GROUPS";

DROP TABLE "ACCOUNT"."GROUP_ROLES";

DROP TABLE "ACCOUNT"."MODULES";

DROP TABLE "ACCOUNT"."ROLES";

DROP TABLE "ACCOUNT"."ROLE_MODULES";

DROP TABLE "ACCOUNT"."USERS";

DROP TABLE "ACCOUNT"."USER_EVENTS";

DROP TABLE "ACCOUNT"."USER_EVENT_DATA";

DROP TABLE "ACCOUNT"."USER_GROUPS";

DROP TABLE "ACCOUNT"."USER_RAIONS";

DROP TABLE "ACCOUNT"."USER_ROLES";

DROP TABLE "DICT"."EVENT_ACTIONS";

DROP TABLE "DICT"."EVENT_DATA_TYPES";

DROP TABLE "DICT"."EVENT_TARGETS";

DROP TABLE "DICT"."RAIONS";

DROP TABLE "DICT"."REQUEST_STATES";

DROP TABLE "DICT"."REQUEST_TYPES";

DROP TABLE "MQ"."REQUESTS";

DROP SCHEMA "ACCOUNT" RESTRICT;

DROP SCHEMA "DICT" RESTRICT;

DROP SCHEMA "MQ" RESTRICT;

CREATE SCHEMA "ACCOUNT";

CREATE SCHEMA "DICT";

CREATE SCHEMA "MQ";

CREATE TABLE "ACCOUNT"."GROUPS" (
		"ID_GROUP" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."GROUP_ROLES" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_GROUP" BIGINT NOT NULL, 
		"ID_ROLE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."MODULES" (
		"ID_MODULE" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."ROLES" (
		"ID_ROLE" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."ROLE_MODULES" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_ROLE" BIGINT NOT NULL, 
		"ID_MODULE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USERS" (
		"ID_USER" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"LOGIN" VARCHAR(20) NOT NULL, 
		"PASS" VARCHAR(32) NOT NULL, 
		"IS_ACTIVE" CHAR(1) NOT NULL, 
		"NAME" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255), 
		"PASS_DATE" DATE
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_EVENTS" (
		"ID_EVENT" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_TARGET" INTEGER NOT NULL, 
		"ID_ACTION" INTEGER NOT NULL, 
		"STAMP" TIMESTAMP NOT NULL, 
		"TARGET_ID" BIGINT, 
		"TARGET_NAME" VARCHAR(255), 
		"MESSAGE" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_EVENT_DATA" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_EVENT" BIGINT NOT NULL, 
		"ID_TYPE" INTEGER NOT NULL, 
		"JSON" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_GROUPS" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_GROUP" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_RAIONS" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_RAION" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "ACCOUNT"."USER_ROLES" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_ROLE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."EVENT_ACTIONS" (
		"ID_ACTION" INTEGER NOT NULL, 
		"ACTION" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."EVENT_DATA_TYPES" (
		"ID_TYPE" INTEGER NOT NULL, 
		"TYPE" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."EVENT_TARGETS" (
		"ID_TARGET" INTEGER NOT NULL, 
		"TARGET" VARCHAR(120) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."RAIONS" (
		"ID_RAION" INTEGER NOT NULL, 
		"NAME" VARCHAR(200) NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."REQUEST_STATES" (
		"ID_STATE" INTEGER NOT NULL, 
		"STATE" VARCHAR(100) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "DICT"."REQUEST_TYPES" (
		"ID_TYPE" INTEGER NOT NULL, 
		"TYPE" VARCHAR(100) NOT NULL, 
		"DESC" VARCHAR(255)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "MQ"."REQUESTS" (
		"ID_REQUEST" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"ID_USER" BIGINT NOT NULL, 
		"ID_TYPE" INTEGER NOT NULL, 
		"ID_STATE" INTEGER NOT NULL, 
		"JSON" VARCHAR(500), 
		"GUID" VARCHAR(100), 
		"CREATED" TIMESTAMP NOT NULL, 
		"PROCESSED" TIMESTAMP, 
		"DELIVERED" TIMESTAMP, 
		"MESSAGE" VARCHAR(500)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "ACCOUNT"."GROUPS" ADD CONSTRAINT "GROUPS_PK" PRIMARY KEY
	("ID_GROUP");

ALTER TABLE "ACCOUNT"."GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."MODULES" ADD CONSTRAINT "MODULES_PK" PRIMARY KEY
	("ID_MODULE");

ALTER TABLE "ACCOUNT"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY
	("ID_ROLE");

ALTER TABLE "ACCOUNT"."ROLE_MODULES" ADD CONSTRAINT "ROLE_MODULES_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY
	("ID_USER");

ALTER TABLE "ACCOUNT"."USER_EVENTS" ADD CONSTRAINT "USER_EVENTS_PK" PRIMARY KEY
	("ID_EVENT");

ALTER TABLE "ACCOUNT"."USER_EVENT_DATA" ADD CONSTRAINT "USER_EVENT_ACTIONS_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_PK" PRIMARY KEY
	("ID");

ALTER TABLE "ACCOUNT"."USER_RAIONS" ADD CONSTRAINT "USER_RAIONS_PK" PRIMARY KEY
	("ID_USER", 
	 "ID_RAION", 
	 "ID");

ALTER TABLE "ACCOUNT"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_PK" PRIMARY KEY
	("ID");

ALTER TABLE "DICT"."EVENT_ACTIONS" ADD CONSTRAINT "EVENT_ACTIONS_PK" PRIMARY KEY
	("ID_ACTION");

ALTER TABLE "DICT"."EVENT_DATA_TYPES" ADD CONSTRAINT "EVENT_DATA_TYPES_PK" PRIMARY KEY
	("ID_TYPE");

ALTER TABLE "DICT"."EVENT_TARGETS" ADD CONSTRAINT "ACTIVITY_TARGETS_PK" PRIMARY KEY
	("ID_TARGET");

ALTER TABLE "DICT"."RAIONS" ADD CONSTRAINT "RAIONS_PK" PRIMARY KEY
	("ID_RAION");

ALTER TABLE "DICT"."REQUEST_STATES" ADD CONSTRAINT "REQUEST_STATES_PK" PRIMARY KEY
	("ID_STATE");

ALTER TABLE "DICT"."REQUEST_TYPES" ADD CONSTRAINT "REQUEST_TYPES_PK" PRIMARY KEY
	("ID_TYPE");

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_PK" PRIMARY KEY
	("ID_REQUEST");

ALTER TABLE "ACCOUNT"."GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_GROUPS_FK" FOREIGN KEY
	("ID_GROUP")
	REFERENCES "ACCOUNT"."GROUPS"
	("ID_GROUP")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_ROLES_FK" FOREIGN KEY
	("ID_ROLE")
	REFERENCES "ACCOUNT"."ROLES"
	("ID_ROLE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."ROLE_MODULES" ADD CONSTRAINT "ROLE_MODULES_MODULES_FK" FOREIGN KEY
	("ID_MODULE")
	REFERENCES "ACCOUNT"."MODULES"
	("ID_MODULE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."ROLE_MODULES" ADD CONSTRAINT "ROLE_MODULES_ROLES_FK" FOREIGN KEY
	("ID_ROLE")
	REFERENCES "ACCOUNT"."ROLES"
	("ID_ROLE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_EVENTS" ADD CONSTRAINT "USER_EVENTS_EVENT_ACTIONS_FK" FOREIGN KEY
	("ID_ACTION")
	REFERENCES "DICT"."EVENT_ACTIONS"
	("ID_ACTION")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_EVENTS" ADD CONSTRAINT "USER_EVENTS_EVENT_TARGETS_FK" FOREIGN KEY
	("ID_TARGET")
	REFERENCES "DICT"."EVENT_TARGETS"
	("ID_TARGET")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_EVENTS" ADD CONSTRAINT "USER_EVENTS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_EVENT_DATA" ADD CONSTRAINT "USER_EVENT_DATA_EVENT_DATA_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."EVENT_DATA_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_EVENT_DATA" ADD CONSTRAINT "USER_EVENT_DATA_USER_EVENTS_FK" FOREIGN KEY
	("ID_EVENT")
	REFERENCES "ACCOUNT"."USER_EVENTS"
	("ID_EVENT")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_GROUPS_FK" FOREIGN KEY
	("ID_GROUP")
	REFERENCES "ACCOUNT"."GROUPS"
	("ID_GROUP")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_RAIONS" ADD CONSTRAINT "USER_RAIONS_RAIONS_FK" FOREIGN KEY
	("ID_RAION")
	REFERENCES "DICT"."RAIONS"
	("ID_RAION")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_RAIONS" ADD CONSTRAINT "USER_RAIONS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_ROLES_FK" FOREIGN KEY
	("ID_ROLE")
	REFERENCES "ACCOUNT"."ROLES"
	("ID_ROLE")
	ON DELETE CASCADE;

ALTER TABLE "ACCOUNT"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_REQUEST_STATES_FK" FOREIGN KEY
	("ID_STATE")
	REFERENCES "DICT"."REQUEST_STATES"
	("ID_STATE")
	ON DELETE CASCADE;

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_REQUEST_TYPES_FK" FOREIGN KEY
	("ID_TYPE")
	REFERENCES "DICT"."REQUEST_TYPES"
	("ID_TYPE")
	ON DELETE CASCADE;

ALTER TABLE "MQ"."REQUESTS" ADD CONSTRAINT "REQUESTS_USERS_FK" FOREIGN KEY
	("ID_USER")
	REFERENCES "ACCOUNT"."USERS"
	("ID_USER")
	ON DELETE CASCADE;

COMMENT ON COLUMN "ACCOUNT"."GROUPS"."DESC" IS
'Group description';

COMMENT ON COLUMN "ACCOUNT"."GROUPS"."ID_GROUP" IS
'Identity field of a group';

COMMENT ON COLUMN "ACCOUNT"."GROUPS"."NAME" IS
'Group name';

COMMENT ON COLUMN "ACCOUNT"."GROUP_ROLES"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."GROUP_ROLES"."ID_GROUP" IS
'Foreign key to access group';

COMMENT ON COLUMN "ACCOUNT"."GROUP_ROLES"."ID_ROLE" IS
'Foreign key to access role';

COMMENT ON COLUMN "ACCOUNT"."MODULES"."DESC" IS
'Description of module';

COMMENT ON COLUMN "ACCOUNT"."MODULES"."ID_MODULE" IS
'Identity field of module';

COMMENT ON COLUMN "ACCOUNT"."MODULES"."NAME" IS
'Name of module';

COMMENT ON COLUMN "ACCOUNT"."ROLES"."DESC" IS
'Role description';

COMMENT ON COLUMN "ACCOUNT"."ROLES"."ID_ROLE" IS
'Identity field of a role';

COMMENT ON COLUMN "ACCOUNT"."ROLES"."NAME" IS
'Role name';

COMMENT ON COLUMN "ACCOUNT"."ROLE_MODULES"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."ROLE_MODULES"."ID_MODULE" IS
'Foreign key to access module';

COMMENT ON COLUMN "ACCOUNT"."ROLE_MODULES"."ID_ROLE" IS
'Foreign key to access role';

COMMENT ON COLUMN "ACCOUNT"."USERS"."DESC" IS
'Description of user';

COMMENT ON COLUMN "ACCOUNT"."USERS"."ID_USER" IS
'Identification field of user';

COMMENT ON COLUMN "ACCOUNT"."USERS"."IS_ACTIVE" IS
'Is user active (T - yes F - no)';

COMMENT ON COLUMN "ACCOUNT"."USERS"."LOGIN" IS
'Login field';

COMMENT ON COLUMN "ACCOUNT"."USERS"."NAME" IS
'User name (as shown in application, different from the field user was authorized with)';

COMMENT ON COLUMN "ACCOUNT"."USERS"."PASS" IS
'User password (stored as hash)';

COMMENT ON COLUMN "ACCOUNT"."USERS"."PASS_DATE" IS
'Password expiration date';

COMMENT ON COLUMN "ACCOUNT"."USER_GROUPS"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."USER_GROUPS"."ID_GROUP" IS
'Foreign key to access group';

COMMENT ON COLUMN "ACCOUNT"."USER_GROUPS"."ID_USER" IS
'Foreign key to user';

COMMENT ON COLUMN "ACCOUNT"."USER_RAIONS"."ID" IS
'Indentity field of a link';

COMMENT ON COLUMN "ACCOUNT"."USER_RAIONS"."ID_RAION" IS
'Raion number';

COMMENT ON COLUMN "ACCOUNT"."USER_RAIONS"."ID_USER" IS
'Foreign key to user';

COMMENT ON COLUMN "ACCOUNT"."USER_ROLES"."ID" IS
'Identity field of a link';

COMMENT ON COLUMN "ACCOUNT"."USER_ROLES"."ID_ROLE" IS
'Foreign key to access role';

COMMENT ON COLUMN "ACCOUNT"."USER_ROLES"."ID_USER" IS
'Foreign key to user';

COMMENT ON COLUMN "DICT"."RAIONS"."ID_RAION" IS
'Raion number';

COMMENT ON COLUMN "DICT"."RAIONS"."NAME" IS
'Raion name';

COMMENT ON COLUMN "DICT"."REQUEST_STATES"."DESC" IS
'State description';

COMMENT ON COLUMN "DICT"."REQUEST_STATES"."ID_STATE" IS
'Identity of state';

COMMENT ON COLUMN "DICT"."REQUEST_STATES"."STATE" IS
'State name';

COMMENT ON COLUMN "DICT"."REQUEST_TYPES"."DESC" IS
'Type description';

COMMENT ON COLUMN "DICT"."REQUEST_TYPES"."ID_TYPE" IS
'Identity of type';

COMMENT ON COLUMN "DICT"."REQUEST_TYPES"."TYPE" IS
'Type name';

COMMENT ON COLUMN "MQ"."REQUESTS"."CREATED" IS
'Date and time of creating request';

COMMENT ON COLUMN "MQ"."REQUESTS"."DELIVERED" IS
'Date and time of delivering request result';

COMMENT ON COLUMN "MQ"."REQUESTS"."GUID" IS
'GUID of request';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_REQUEST" IS
'Identity of request';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_STATE" IS
'Identity of state';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_TYPE" IS
'Identity of type';

COMMENT ON COLUMN "MQ"."REQUESTS"."ID_USER" IS
'Foreign key to user who created the request';

COMMENT ON COLUMN "MQ"."REQUESTS"."JSON" IS
'JSON parameters of request';

COMMENT ON COLUMN "MQ"."REQUESTS"."MESSAGE" IS
'Message';

COMMENT ON COLUMN "MQ"."REQUESTS"."PROCESSED" IS
'Date and time of finishing processing request';

COMMENT ON SCHEMA "ACCOUNT" IS
'Tables for storing application access data';

COMMENT ON SCHEMA "DICT" IS
'Tables for storing dictionaries';

COMMENT ON SCHEMA "MQ" IS
'Tables for storing message query related data';

COMMENT ON TABLE "ACCOUNT"."GROUPS" IS
'Table of user groups (used to group application roles into access groups)';

COMMENT ON TABLE "ACCOUNT"."GROUP_ROLES" IS
'Table of grouping roles into groups';

COMMENT ON TABLE "ACCOUNT"."MODULES" IS
'Table of modules in application (this is used in frontend application to grant or deny access to certain functions)';

COMMENT ON TABLE "ACCOUNT"."ROLES" IS
'Table of user roles (used to group modules into access roles)';

COMMENT ON TABLE "ACCOUNT"."ROLE_MODULES" IS
'Table of grouping modules into roles';

COMMENT ON TABLE "ACCOUNT"."USERS" IS
'Table of application users';

COMMENT ON TABLE "ACCOUNT"."USER_GROUPS" IS
'Table of linking users to access groups';

COMMENT ON TABLE "ACCOUNT"."USER_RAIONS" IS
'Table of linking users to raion dictionary';

COMMENT ON TABLE "ACCOUNT"."USER_ROLES" IS
'Table of linking users to access roles (in addition to all roles that were provided in user''s access group)';

COMMENT ON TABLE "DICT"."RAIONS" IS
'Dictionary of raions';

COMMENT ON TABLE "DICT"."REQUEST_STATES" IS
'Dictionary of message query request states';

COMMENT ON TABLE "DICT"."REQUEST_TYPES" IS
'Dictionary of message query request types';

COMMENT ON TABLE "MQ"."REQUESTS" IS
'Table of message query requests';

