-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "ACCOUNT"."GROUPS"
(
)
;

CREATE TABLE IF NOT EXISTS "ACCOUNT"."GROUP_ROLES"
(
)
;

CREATE TABLE IF NOT EXISTS "ACCOUNT"."MODULES"
(
    "ID_MODULE" bigint NOT NULL,
    "NAME" character varying(120) NOT NULL,
    "DESC" character varying(255),
    PRIMARY KEY ("ID_MODULE")
);

CREATE TABLE IF NOT EXISTS "ACCOUNT"."ROLES"
(
)
;

CREATE TABLE IF NOT EXISTS "ACCOUNT"."ROLE_MODULES"
(
)
;

CREATE TABLE IF NOT EXISTS "ACCOUNT"."USERS"
(
    "ID_USER" bigint,
    PRIMARY KEY ("ID_USER")
);

CREATE TABLE IF NOT EXISTS "ACCOUNT"."USER_AUTHS"
(
)
;

CREATE TABLE IF NOT EXISTS "ACCOUNT"."USER_GROUPS"
(
)
;

CREATE TABLE IF NOT EXISTS "ACCOUNT"."USER_ROLES"
(
)
;

CREATE TABLE IF NOT EXISTS "DICT"."REQUEST_STATES"
(
)
;

CREATE TABLE IF NOT EXISTS "DICT"."REQUEST_TYPES"
(
)
;

CREATE TABLE IF NOT EXISTS "MQ"."REQUESTS"
(
)
;
END;