CREATE TABLE [MQ].[REQUESTS]
(
  [IdRequest] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [IdUser] BIGINT NOT NULL FOREIGN KEY REFERENCES [ACCOUNT].[USERS],
  [IdType] INT NOT NULL FOREIGN KEY REFERENCES [DICT].[REQUEST_TYPES],
  [IdState] INT NOT NULL FOREIGN KEY REFERENCES [DICT].[REQUEST_STATES],
  [JSON] VARCHAR(500),
  [GUID] VARCHAR(100),
  [Created] DATE NOT NULL,
  [Processed] DATE,
  [Delivered] DATE,
  [Message] VARCHAR(500)
)
