CREATE TABLE [R].[RSCRIPTS]
(
  [IdRScript] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [ScriptFile] VARCHAR(255) NOT NULL,
  [Name] VARCHAR(120) NOT NULL,
  [ContentType] VARCHAR(50) NOT NULL,
  [ResultFile] VARCHAR(200) NOT NULL,
  [Desc] VARCHAR(255)
)
