CREATE TABLE [R].[RSCRIPT_TREE]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [IdParent] BIGINT,
  [IdRScript] BIGINT FOREIGN KEY REFERENCES [R].[RSCRIPTS],
  [Name] VARCHAR(120),
  [Modules] VARCHAR(255),
  [Icon] VARCHAR(50),
  [Color] VARCHAR(50),
  [Desc] VARCHAR(255)
)
