-- SCHEMA --
CREATE SCHEMA [ACCOUNT] 
GO
CREATE SCHEMA [DICT] 
GO
CREATE SCHEMA [MQ] 
GO
CREATE SCHEMA [R] 
GO
CREATE SCHEMA [SAMPLE] 
GO

-- DROP EXISTING --
DROP VIEW [ACCOUNT].[V_AUDIT]
DROP VIEW [ACCOUNT].[V_AUDIT_DATA]

DROP TABLE [SAMPLE].[SAMPLE_AUDIT_DATA]
DROP TABLE [SAMPLE].[SAMPLE_AUDIT]
DROP TABLE [SAMPLE].[SAMPLE_CHILD]
DROP TABLE [SAMPLE].[SAMPLE]

DROP TABLE [R].[RSCRIPT_TREE]
DROP TABLE [R].[RSCRIPT_PARAMS]
DROP TABLE [R].[RSCRIPTS]

DROP TABLE [MQ].[REQUESTS]

DROP TABLE [ACCOUNT].[USER_DISTRICTS]
DROP TABLE [ACCOUNT].[USER_AUDIT_DATA]
DROP TABLE [ACCOUNT].[USER_AUDIT]
DROP TABLE [ACCOUNT].[GROUP_ROLES]
DROP TABLE [ACCOUNT].[ROLE_MODULES]
DROP TABLE [ACCOUNT].[USER_GROUPS]
DROP TABLE [ACCOUNT].[USER_ROLES]
DROP TABLE [ACCOUNT].[USERS]
DROP TABLE [ACCOUNT].[GROUPS]
DROP TABLE [ACCOUNT].[MODULES]
DROP TABLE [ACCOUNT].[ROLES]

DROP TABLE [DICT].[AUDIT_ACTIONS]
DROP TABLE [DICT].[AUDIT_DATA_TYPES]
DROP TABLE [DICT].[AUDIT_TARGETS]
DROP TABLE [DICT].[DISTRICTS]
DROP TABLE [DICT].[REQUEST_STATES]
DROP TABLE [DICT].[REQUEST_TYPES]
DROP TABLE [DICT].[RSCRIPT_PARAM_TYPES]
DROP TABLE [DICT].[SAMPLE_DICTS]
DROP TABLE [DICT].[SAMPLE_TYPES]
GO

-- CREATE TABLES --
-- DICT --
CREATE TABLE [DICT].[AUDIT_ACTIONS]
(
  [IdAction] INT NOT NULL,
  [Action] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_AUDIT_ACTIONS] PRIMARY KEY ([IdAction] ASC)
) 

CREATE TABLE [DICT].[AUDIT_DATA_TYPES]
(
  [IdType] INT NOT NULL,
  [Type] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_AUDIT_DATA_TYPES] PRIMARY KEY ([IdType] ASC)
) 

CREATE TABLE [DICT].[AUDIT_TARGETS]
(
  [IdTarget] INT NOT NULL,
  [Target] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_AUDIT_TARGETS] PRIMARY KEY ([IdTarget] ASC)
) 

CREATE TABLE [DICT].[DISTRICTS]
(
  [IdDistrict] INT NOT NULL,
  [Name] VARCHAR(200),

  CONSTRAINT [PK_DICT_DISTRICTS] PRIMARY KEY ([IdDistrict] ASC)
) 

CREATE TABLE [DICT].[REQUEST_STATES]
(
  [IdState] INT NOT NULL,
  [State] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_REQUEST_STATES] PRIMARY KEY ([IdState] ASC)
) 

CREATE TABLE [DICT].[REQUEST_TYPES]
(
  [IdType] INT NOT NULL,
  [Type] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_REQUEST_TYPES] PRIMARY KEY ([IdType] ASC)
) 

CREATE TABLE [DICT].[RSCRIPT_PARAM_TYPES]
(
  [IdType] INT NOT NULL,
  [Type] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_RSCRIPT_PARAM_TYPES] PRIMARY KEY ([IdType] ASC)
) 

CREATE TABLE [DICT].[SAMPLE_DICTS]
(
  [IdDict] BIGINT NOT NULL IDENTITY(1,1),
  [Dict] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_SAMPLE_DICTS] PRIMARY KEY ([IdDict] ASC)
) 

CREATE TABLE [DICT].[SAMPLE_TYPES]
(
  [IdType] INT NOT NULL,
  [Type] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_DICT_SAMPLE_TYPES] PRIMARY KEY ([IdType] ASC)
) 

-- ACCOUNT --
CREATE TABLE [ACCOUNT].[USERS]
(
  [IdUser] BIGINT NOT NULL IDENTITY(1,1),
  [Login] VARCHAR(20) NOT NULL,
  [Pass] VARCHAR(32) NOT NULL,
  [IsActive] CHAR(1) NOT NULL,
  [Name] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),
  [PassDate] DATE,

  CONSTRAINT [PK_ACCOUNT_USERS] PRIMARY KEY ([IdUser] ASC)
) 

CREATE TABLE [ACCOUNT].[GROUPS]
(
  [IdGroup] BIGINT NOT NULL IDENTITY(1,1),
  [Name] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_ACCOUNT_GROUPS] PRIMARY KEY ([IdGroup] ASC)
) 

CREATE TABLE [ACCOUNT].[MODULES]
(
  [IdModule] BIGINT NOT NULL IDENTITY(1,1),
  [Name] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_ACCOUNT_MODULES] PRIMARY KEY ([IdModule] ASC)
) 

CREATE TABLE [ACCOUNT].[ROLES]
(
  [IdRole] BIGINT NOT NULL IDENTITY(1,1),
  [Name] VARCHAR(120) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_ACCOUNT_ROLES] PRIMARY KEY ([IdRole] ASC)
) 

CREATE TABLE [ACCOUNT].[GROUP_ROLES]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdGroup] BIGINT NOT NULL,
  [IdRole] BIGINT NOT NULL,

  CONSTRAINT [PK_ACCOUNT_GROUP_ROLES] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_ACCOUNT_GROUP_ROLES_GROUPS] FOREIGN KEY ([IdGroup]) REFERENCES [ACCOUNT].[GROUPS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_GROUP_ROLES_ROLES] FOREIGN KEY ([IdRole]) REFERENCES [ACCOUNT].[ROLES] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [ACCOUNT].[ROLE_MODULES]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdRole] BIGINT NOT NULL,
  [IdModule] BIGINT NOT NULL,

  CONSTRAINT [PK_ACCOUNT_ROLE_MODULES] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_ACCOUNT_ROLE_MODULES_ROLES] FOREIGN KEY ([IdRole]) REFERENCES [ACCOUNT].[ROLES] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_ROLE_MODULES_MODULES] FOREIGN KEY ([IdModule]) REFERENCES [ACCOUNT].[MODULES] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [ACCOUNT].[USER_GROUPS]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdUser] BIGINT NOT NULL,
  [IdGroup] BIGINT NOT NULL,

  CONSTRAINT [PK_ACCOUNT_USER_GROUPS] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_ACCOUNT_USER_GROUPS_USERS] FOREIGN KEY ([IdUser]) REFERENCES [ACCOUNT].[USERS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_USER_GROUPS_GROUPS] FOREIGN KEY ([IdGroup]) REFERENCES [ACCOUNT].[GROUPS] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [ACCOUNT].[USER_ROLES]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdUser] BIGINT NOT NULL,
  [IdRole] BIGINT NOT NULL,

  CONSTRAINT [PK_ACCOUNT_USER_ROLES] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_ACCOUNT_USER_ROLES_USERS] FOREIGN KEY ([IdUser]) REFERENCES [ACCOUNT].[USERS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_USER_ROLES_ROLES] FOREIGN KEY ([IdRole]) REFERENCES [ACCOUNT].[ROLES] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [ACCOUNT].[USER_DISTRICTS]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdUser] BIGINT NOT NULL,
  [IdDistrict] INT NOT NULL,

  CONSTRAINT [PK_ACCOUNT_USER_DISTRICTS] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_ACCOUNT_USER_DISTRICTS_USERS] FOREIGN KEY ([IdUser]) REFERENCES [ACCOUNT].[USERS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_USER_DISTRICTS_DISTRICTS] FOREIGN KEY ([IdDistrict]) REFERENCES [DICT].[DISTRICTS] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [ACCOUNT].[USER_AUDIT]
(
  [IdAudit] BIGINT NOT NULL IDENTITY(1,1),
  [IdUser] BIGINT NOT NULL,
  [IdTarget] INT NOT NULL,
  [IdAction] INT NOT NULL,
  [Stamp] DATETIME NOT NULL,
  [TargetId] BIGINT,
  [TargetName] VARCHAR(255),
  [Message] VARCHAR(255),

  CONSTRAINT [PK_ACCOUNT_USER_AUDIT] PRIMARY KEY ([IdAudit] ASC),
  CONSTRAINT [FK_ACCOUNT_USER_AUDIT_USERS] FOREIGN KEY ([IdUser]) REFERENCES [ACCOUNT].[USERS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_USER_AUDIT_AUDIT_TARGETS] FOREIGN KEY ([IdTarget]) REFERENCES [DICT].[AUDIT_TARGETS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_USER_AUDIT_AUDIT_ACTIONS] FOREIGN KEY ([IdAction]) REFERENCES [DICT].[AUDIT_ACTIONS] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [ACCOUNT].[USER_AUDIT_DATA]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdAudit] BIGINT NOT NULL,
  [IdType] INT NOT NULL,
  [JSON] VARCHAR(255),

  CONSTRAINT [PK_ACCOUNT_USER_AUDIT_DATA] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_ACCOUNT_USER_AUDIT_DATA_USER_AUDIT] FOREIGN KEY ([IdAudit]) REFERENCES [ACCOUNT].[USER_AUDIT] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_ACCOUNT_USER_AUDIT_DATA_AUDIT_DATA_TYPES] FOREIGN KEY ([IdType]) REFERENCES [DICT].[AUDIT_DATA_TYPES] ON DELETE CASCADE ON UPDATE CASCADE
) 

-- MESSAGE QUERY --
CREATE TABLE [MQ].[REQUESTS]
(
  [IdRequest] BIGINT NOT NULL IDENTITY(1,1),
  [IdUser] BIGINT NOT NULL,
  [IdType] INT NOT NULL,
  [IdState] INT NOT NULL,
  [JSON] VARCHAR(500),
  [GUID] VARCHAR(100),
  [Created] DATE NOT NULL,
  [Processed] DATE,
  [Delivered] DATE,
  [Message] VARCHAR(500),

  CONSTRAINT [PK_MQ_REQUESTS] PRIMARY KEY ([IdRequest] ASC),
  CONSTRAINT [FK_MQ_REQUESTS_USERS] FOREIGN KEY ([IdUser]) REFERENCES [ACCOUNT].[USERS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_MQ_REQUESTS_REQUEST_TYPES] FOREIGN KEY ([IdType]) REFERENCES [DICT].[REQUEST_TYPES] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_MQ_REQUESTS_REQUEST_STATES] FOREIGN KEY ([IdState]) REFERENCES [DICT].[REQUEST_STATES] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [R].[RSCRIPTS]
(
  [IdRScript] BIGINT NOT NULL IDENTITY(1,1),
  [ScriptFile] VARCHAR(255) NOT NULL,
  [Name] VARCHAR(120) NOT NULL,
  [ContentType] VARCHAR(50) NOT NULL,
  [ResultFile] VARCHAR(200) NOT NULL,
  [Description] VARCHAR(255),

  CONSTRAINT [PK_R_RSCRIPTS] PRIMARY KEY ([IdRScript] ASC)
) 

CREATE TABLE [R].[RSCRIPT_PARAMS]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdRScript] BIGINT NOT NULL,
  [IdType] INT NOT NULL,
  [Name] VARCHAR(120) NOT NULL,
  [Hint] VARCHAR(255),
  [Description] VARCHAR(255),

  CONSTRAINT [PK_R_RSCRIPT_PARAMS] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_R_RSCRIPT_PARAMS_RSCRIPTS] FOREIGN KEY ([IdRScript]) REFERENCES [R].[RSCRIPTS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_R_RSCRIPT_PARAMS_RSCRIPT_PARAM_TYPES] FOREIGN KEY ([IdType]) REFERENCES [DICT].[RSCRIPT_PARAM_TYPES] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [R].[RSCRIPT_TREE]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdParent] BIGINT,
  [IdRScript] BIGINT,
  [Name] VARCHAR(120),
  [Modules] VARCHAR(255),
  [Icon] VARCHAR(50),
  [Color] VARCHAR(50),
  [Description] VARCHAR(255),

  CONSTRAINT [PK_R_RSCRIPT_TREE] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_R_RSCRIPT_TREE_RSCRIPTS] FOREIGN KEY ([IdRScript]) REFERENCES [R].[RSCRIPTS] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [SAMPLE].[SAMPLE]
(
  [IdSample] BIGINT NOT NULL IDENTITY(1,1),
  [IdDistrict] INT NOT NULL,
  [IdType] INT NOT NULL,
  [IdDict] BIGINT NOT NULL,
  [Text] VARCHAR(120),
  [Number] BIGINT,
  [Date] DATE,
  [Timestamp] DATETIME,
  [Sum] DECIMAL(10,2),

  CONSTRAINT [PK_SAMPLE_SAMPLE] PRIMARY KEY ([IdSample] ASC),
  CONSTRAINT [FK_SAMPLE_SAMPLE_DISTRICTS] FOREIGN KEY ([IdDistrict]) REFERENCES [DICT].[DISTRICTS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_SAMPLE_SAMPLE_SAMPLE_TYPES] FOREIGN KEY ([IdType]) REFERENCES [DICT].[SAMPLE_TYPES] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_SAMPLE_SAMPLE_SAMPLE_DICTS] FOREIGN KEY ([IdDict]) REFERENCES [DICT].[SAMPLE_DICTS] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [SAMPLE].[SAMPLE_CHILD]
(
  [IdChild] BIGINT NOT NULL IDENTITY(1,1),
  [IdSample] BIGINT NOT NULL,
  [Text] VARCHAR(120),

  CONSTRAINT [PK_SAMPLE_SAMPLE_CHILD] PRIMARY KEY ([IdChild] ASC),
  CONSTRAINT [FK_SAMPLE_SAMPLE_CHILD_SAMPLE] FOREIGN KEY ([IdSample]) REFERENCES [SAMPLE].[SAMPLE] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [SAMPLE].[SAMPLE_AUDIT]
(
  [IdAudit] BIGINT NOT NULL IDENTITY(1,1),
  [IdUser] BIGINT NOT NULL,
  [IdTarget] INT NOT NULL,
  [IdAction] INT NOT NULL,
  [Stamp] DATETIME NOT NULL,
  [TargetId] BIGINT,
  [TargetName] VARCHAR(255),
  [Message] VARCHAR(255),

  CONSTRAINT [PK_SAMPLE_SAMPLE_AUDIT] PRIMARY KEY ([IdAudit] ASC),
  CONSTRAINT [FK_SAMPLE_SAMPLE_AUDIT_USERS] FOREIGN KEY ([IdUser]) REFERENCES [ACCOUNT].[USERS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_SAMPLE_SAMPLE_AUDIT_AUDIT_TARGETS] FOREIGN KEY ([IdTarget]) REFERENCES [DICT].[AUDIT_TARGETS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_SAMPLE_SAMPLE_AUDIT_AUDIT_ACTIONS] FOREIGN KEY ([IdAction]) REFERENCES [DICT].[AUDIT_ACTIONS] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_SAMPLE_SAMPLE_AUDIT_SAMPLE] FOREIGN KEY ([TargetId]) REFERENCES [SAMPLE].[SAMPLE] ON DELETE CASCADE ON UPDATE CASCADE
) 

CREATE TABLE [SAMPLE].[SAMPLE_AUDIT_DATA]
(
  [Id] BIGINT NOT NULL IDENTITY(1,1),
  [IdAudit] BIGINT NOT NULL,
  [IdType] INT NOT NULL,
  [JSON] VARCHAR(255),

  CONSTRAINT [PK_SAMPLE_SAMPLE_AUDIT_DATA] PRIMARY KEY ([Id] ASC),
  CONSTRAINT [FK_SAMPLE_SAMPLE_AUDIT_DATA_SAMPLE] FOREIGN KEY ([IdAudit]) REFERENCES [SAMPLE].[SAMPLE] ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_SAMPLE_SAMPLE_AUDIT_DATA_AUDIT_DATA_TYPES] FOREIGN KEY ([IdType]) REFERENCES [DICT].[AUDIT_DATA_TYPES] ON DELETE CASCADE ON UPDATE CASCADE
) 

GO

CREATE VIEW [ACCOUNT].[V_AUDIT]
  AS 
    SELECT
      'USER' AS [Source],
      U.[IdAudit],
      U.[IdUser],
      UU.[Login],
      U.[IdTarget],
      UAT.[Target],
      UAT.[Description] AS [TargetDesc],
      U.[IdAction],
      UAA.[Description] AS [Action],
      U.[Stamp],
      U.[TargetId],
      U.[TargetName],
      U.[Message]
    FROM [ACCOUNT].[USER_AUDIT] U
      JOIN [ACCOUNT].[USERS] UU ON U.[IdUser] = UU.[IdUser]
      JOIN [DICT].[AUDIT_ACTIONS] UAA ON U.[IdAction] = UAA.[IdAction]
      JOIN [DICT].[AUDIT_TARGETS] UAT ON U.[IdTarget] = UAT.[IdTarget]
  UNION ALL
    SELECT
      'SAMPLE' as [Source],
      S.[IdAudit],
      S.[IdUser],
      SU.[Login],
      S.[IdTarget],
      SAT.[Target],
      SAT.[Description] AS [TargetDesc],
      S.[IdAction],
      SAA.[Description] AS [Action],
      S.[Stamp],
      S.[TargetId],
      S.[TargetName],
      S.[Message]
    FROM [SAMPLE].[SAMPLE_AUDIT] S
      JOIN [ACCOUNT].[USERS] SU ON S.[IdUser] = SU.[IdUser]
      JOIN [DICT].[AUDIT_ACTIONS] SAA ON S.[IdAction] = SAA.[IdAction]
      JOIN [DICT].[AUDIT_TARGETS] SAT ON S.[IdTarget] = SAT.[IdTarget] 

GO

CREATE VIEW [ACCOUNT].[V_AUDIT_DATA]
  AS
    SELECT
      'USER' as [Source],
      U.[Id],
      U.[IdAudit],
      U.[IdType],
      UT.[Type],
      U.[JSON]
    FROM [ACCOUNT].[USER_AUDIT_DATA] U
      JOIN [DICT].[AUDIT_DATA_TYPES] UT
      ON U.[IdType] = UT.[IdType]
  UNION ALL
    SELECT
      'SAMPLE' as [Source],
      S.[Id],
      S.[IdAudit],
      S.[IdType],
      ST.[Type],
      S.[JSON]
    FROM [SAMPLE].[SAMPLE_AUDIT_DATA] S
      JOIN [DICT].[AUDIT_DATA_TYPES] ST
      ON S.[IdType] = ST.[IdType] 

GO